version: "3.9"

services:
  app:
    build: .
    container_name: vending-machine
    ports:
      - "8000:8000"
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:fakekey
